baseURL = 'https://2p4b.github.io/'
languageCode = 'en-us'
title = '2p4b'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Curious'
pageRef = '/posts'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
